services:
  - type: web
    name: lang-nghe-viet
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lang-nghe-viet-db
          property: connectionString
    plan: free

databases:
  - name: lang-nghe-viet-db
    plan: free
    postDeploy: npm run db:push